# Generated by Django 4.1 on 2023-04-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=180)),
                ('student_password', models.CharField(max_length=180)),
            ],
        ),
    ]
